version: 2.1

orbs:
  moul: moul/build@1.16.0 # https://github.com/moul/build

workflows:
  main:
    jobs:
      - moul/golang-build:
          gopkg: moul.io/number-to-words
      - moul/golang-build:
          gopkg: moul.io/number-to-words
          tag: '1.12'
      - moul/docker-build
